name: airtrail
services:
  airtrail:
    image: johly/airtrail:latest
    container_name: airtrail
    env_file:
      - stack.env
    ports:
      - 11116:3000
    restart: unless-stopped
    network_mode: bridge