name: crontab-guru
services:
  crontab-guru:
    image: ghcr.io/tuannnh/crontab-guru:latest
    container_name: crontab-guru-dashboard
    env_file:
      - stack.env
    volumes:
      - /DATA/AppData/crontab-guru/cronitor/config/:/etc/cronitor/
      - /etc/cron.d:/etc/cron.d
      - /var/spool/cron:/var/spool/cron
      - /etc/crontab:/etc/crontab
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 11144:9000
    restart: unless-stopped
    network_mode: bridge