name: crontab-guru
services:
  crontab-guru:
    image: ghcr.io/tuannnh/crontab-guru:latest
    container_name: crontab-guru-dashboard
    env_file:
      - stack.env
    volumes:
      - /DATA/AppData/crontab-guru/cronitor/config/:/etc/cronitor/
      - /DATA/AppData/crontab-guru/cronitor:/root/.config/cronitor
      - /DATA/AppData/crontab-guru/crontabs:/var/spool/cron/crontabs
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 11144:9000
    restart: unless-stopped
    network_mode: bridge